# integrations/jira.py

import os
import requests

JIRA_URL = os.getenv("JIRA_URL")  # e.g. https://yourcompany.atlassian.net
JIRA_USER = os.getenv("JIRA_USER")  # usually email
JIRA_API_TOKEN = os.getenv("JIRA_API_TOKEN")  # from Atlassian account

def create_jira_issue(project_key: str, summary: str, description: str, issue_type: str = "Task") -> dict:
    """
    Create a new Jira issue.
    Args:
        project_key (str): Jira project key (e.g., "COMPL")
        summary (str): Issue summary/title
        description (str): Issue description (can include LLM output)
        issue_type (str): e.g., "Task", "Bug", "Story"
    Returns:
        dict: JSON response from Jira
    """
    url = f"{JIRA_URL}/rest/api/3/issue"
    auth = (JIRA_USER, JIRA_API_TOKEN)
    headers = {"Accept": "application/json", "Content-Type": "application/json"}
    payload = {
        "fields": {
            "project": {"key": project_key},
            "summary": summary,
            "description": description,
            "issuetype": {"name": issue_type}
        }
    }
    response = requests.post(url, json=payload, auth=auth, headers=headers, timeout=10)
    response.raise_for_status()
    return response.json()

# --- Example usage (for demonstration) ---
if __name__ == "__main__":
    # You can try running: python integrations/jira.py
    import sys
    resp = create_jira_issue(
        project_key="COMPL",
        summary="Test: Compliance gap detected in AC-2",
        description="Generated by RegScale RAG: Quarterly review missing evidence for AC-2."
    )
    print("Jira Issue Created:", resp.get("key"))
